/**
 * @description       : Handler for the Work Order berfore insert trigger.
 * @author            : Sofiane Bazizen (SpringFive)
 * @group             : 
 * @last modified on  : 07-11-2020
 * @last modified by  : Sofiane Bazizen (SpringFive)
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-11-2020   Sofiane Bazizen (SpringFive)   Initial Version
**/
public class DEF_StringHelper {
    
    public static String WO_ORDERTYPE_MAINTENANCE = 'Maintenance';
    public static String WO_REPORT_PREFIX = 'SIR';

}